name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - feature/*

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Run lint checks
        run: |
          flake8 app tests

      - name: Run unit tests
        run: |
          pytest tests

      - name: Build Docker image
        run: |
          docker build -t claims-status-api:test .